name: JoJo-CycleGAN
dependencies:
  - tensorflow-gpu
  - opencv
  - pip
  - pip:
      - numpy
      - Pillow
      - pathlib
      - matplotlib
      - ipython
      - tensorflow-datasets
      - git+https://github.com/somacoder/pix2pix-tensorflow.git
