name: JoJo-CycleGAN
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - tensorflow-gpu
  - opencv
  - pip
  - pip:
      - numpy
      - Pillow
      - pathlib
      - matplotlib
      - ipython
      - tensorflow-datasets
      - https://raw.githubusercontent.com/affinelayer/pix2pix-tensorflow/master/pix2pix.py
