name: JoJo-CycleGAN
dependencies:
  - python=3.10
  - tensorflow-gpu
  - opencv
  - numpy
  - pillow
  - matplotlib
  - ipython
  - pathlib
  - tensorflow-datasets
  - pip
  - pip:
      - git+https://github.com/tensorflow/examples.git
