name: JoJo-CycleGAN
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - tensorflow-gpu
  - opencv
  - pip
  - wget
  - pip:
      - numpy
      - Pillow
      - pathlib
      - matplotlib
      - ipython
      - tensorflow-datasets
post-link:
  - wget https://raw.githubusercontent.com/affinelayer/pix2pix-tensorflow/master/pix2pix.py -O pix2pix.py
