name: JoJo-CycleGAN
dependencies:
  - pip
  - pip:
      - tensorflow
      - opencv-python
      - numpy
      - pillow
      - matplotlib
      - ipython
      - pathlib
      - tensorflow-datasets
      - git+https://github.com/tensorflow/examples.git
